/**
 *
 * @author dongntd@bkav.com on 06/09/2022.
 *
 */

export const hasUserReducers = {
    // [AUTH_ACTION.START_APP.SUCCESS]: SIGN_IN_WORKING[AUTH_ACTION.START_APP.SUCCESS],
    // [AUTH_ACTION.SIGN_IN.SUCCESS]: SIGN_IN_WORKING[AUTH_ACTION.SIGN_IN.SUCCESS],
    // [AUTH_ACTION.SIGN_OUT.SUCCESS]: SIGN_IN_WORKING[AUTH_ACTION.SIGN_OUT.SUCCESS],
};
